add_rules("mode.debug", "mode.release")
set_languages("cxx23")
add_requires("sockpp")
add_defines("NOMINMAX")

target("RakX")
    set_kind("static")
    add_files("src/**.cpp", {public = true})
    add_includedirs("src/", {public = true})
    add_headerfiles("src/**.hpp", {public = true})
    add_packages("sockpp", {public=true})
    set_symbols("debug")

target("RakXPlayground")
    set_kind("binary")
    add_files("RakXPlayground/**.cpp")
    add_includedirs("RakXPlayground/", {public = true})
    add_headerfiles("RakXPlayground/**.hpp", {public = true})
    add_deps("RakX")
    set_symbols("debug")
